### ISSUE TITLE
kakaoSDK version issues

### ISSUE THREAD

**Issue by stmake22** [raccoondev85/kakao-sdk#1]
google developer console issue this:
com.kakao.auth.authorization.authcode.KakaoWebViewActivity->initUi

As a security issue, it seems that you need to upgrade kakaoSDK version to 1.4 or higher. Do you plan to update?

**Comment by raccoondev85** [comment]
Thank you for the feedback, i also noticed the issue.
Just update to version 3.0.0 (fixed the Cross-App Scripting Vulnerability issue as well as the compatibility issue for cordova-android 7 and other new functions are added), then the warning will be disappeared.
